### ISSUE TITLE
multiple Entry

### ISSUE THREAD

**Issue by freezestanley** [freezestanley/vsiren#1]
如果一个项目里有多个html页面，每个页面里有一个路由。即项目里有多套路由时，该如何正确配置vue项目，使能使用`history mode`访问不同页面下的不同路由呢？

`history mode`在这里是指通过`location.pathname`指代对应路径，而非通过`location.hash`模拟。

**Comment by rouberg** [comment]
针对这种问题，在开发环境和生产环境需要不同的配置。
这里不能通过hash模拟路由的原因，一是因为后端框架(比如SSH等)对hash的支持度不是很好，在request和response对象中直接没有API对其操纵，二来，需要和微信平台三方通信时，微信平台对hash支持也不好。

假如我们的SPA部署在index.html上面，分享页面部署在share.html上面。两个html内部都含有路由。
首先，我们需要规划我们的路由，让要服务器能从路径区分出一个路由是属于那个html。一般是通过前缀区分。
比如 /web/a, /web/b, /web/b/more属于index.html这个页面， /share/a, /share/a/a-more, /share/b属于share.html这个页面。这样get请求某个路径，服务器才能知道某个具体的路由应该转发为请求那个根页面。一般来说，webpack配置正确的话，只需要修正html页面的请求即可。

再次，当请求某个路径时，内部重发为请求对应的html。

在开发环境和生产环境需要不同的配置。

两者要做的事情都是一样的，假如路由像上面刚才举例的所示，需要的配置为：

+ 将 `/share/**` 的路由指向 `/share.html`
+ 将 `/web/**` 的路由指向 `/index.html`

开发环境下，我们需要配置webpack的proxyTable， 示例如下：

```javascript
  '/share/**': {
    target: 'http://localhost:9100/',
    pathRewrite: {
      '^\/share(\/[a-zA-Z]+)?': '/share.html'
    }
  }
```

其中，target为当前开发环境的域，注意，需要带上URL schema, 即需要指定协议名称，以及，有些代理设置不成功时，需要在target后面额外加上根路径'/'。

ps： 该方案可以使用`http-proxy-moddleware` 实现，但它不需要设置根路径。并不太清楚上面target需要添加一个'/'是否是属于非预期的bug。
pathRewrite是一个对象，它是key可以传入RegExp对象初始化成一个正则表达式对象。value是要转发到的路径。


生产环境下我们需要配置对应的服务器，具体就不在这儿赘述，只要满足上述的请求服务端重定向即可。
